# -*- coding: utf-8 -*-
"""Wordcloud-g2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqDwdIZKJHH1QUHE5D4Nlcr2oLWWTv2l
"""

# exercise 1
# author Ethan Filliau Lellouche
# state : ongoing